{
 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Import packages"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\tensorboardx.py:41: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\n",
      "  VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\n"
     ]
    }
   ],
   "source": [
    "import sys, os\n",
    "import pathlib\n",
    "# # __location__ = os.getcwd()\n",
    "# # __location__ = pathlib.Path(__location__)\n",
    "\n",
    "sys.path.append('C:\\\\Users\\\\bong\\\\project\\\\snake_RL\\\\dmc\\\\domains')\n",
    "# import snake\n",
    "# import snake_v2\n",
    "# import snake_v3\n",
    "\n",
    "\n",
    "# from snake.envs.SnakeEnv import SnakeEnv # for ray env register\n",
    "# from snake_v2.envs.SnakeEnv import SnakeEnv # for ray env register\n",
    "# from snake_v8_mk1.envs.SnakeEnv import SnakeEnv # for ray env register\n",
    "from snake_v8.envs.SnakeEnv import SnakeEnv # for ray env register\n",
    "import gymnasium as gym\n",
    "\n",
    "# import rl 알고리즘\n",
    "from ray.rllib.algorithms.ppo import PPOConfig \n",
    "from ray.rllib.algorithms.algorithm_config import AlgorithmConfig\n",
    "from ray.rllib.algorithms.algorithm import Algorithm\n",
    "from ray.rllib.policy.policy import Policy\n",
    "\n",
    "from ray.tune.registry import register_env\n",
    "from ray.tune.logger import pretty_print\n",
    "\n",
    "import numpy as np"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Make Snake Env"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:442: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "`UnifiedLogger` will be removed in Ray 2.7.\n",
      "  return UnifiedLogger(config, logdir, loggers=None)\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m 2023-07-14 18:25:56,796\tERROR serialization.py:387 -- No module named 'snake_v8'\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m Traceback (most recent call last):\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m     obj = pickle.loads(in_band)\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m ModuleNotFoundError: No module named 'snake_v8'\u001b[32m [repeated 31x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m 2023-07-14 18:25:56,915\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41340, ip=127.0.0.1, actor_id=57dec7933c9dc73b7c939be201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000018C3EAEE7F0>)\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\u001b[32m [repeated 30x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=41340)\u001b[0m traceback: Traceback (most recent call last):\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "\u001b[2m\u001b[36m(pid=42700)\u001b[0m   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\n",
      "\u001b[2m\u001b[36m(pid=42700)\u001b[0m   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\n",
      "\u001b[2m\u001b[36m(pid=42980)\u001b[0m c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\tensorboardx.py:41: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\n",
      "\u001b[2m\u001b[36m(pid=42980)\u001b[0m   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\n",
      "2023-07-14 18:28:33,449\tERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41664, ip=127.0.0.1, actor_id=24aeb603d0fa6ac4c067d79001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001FDBF48C850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,450\tERROR actor_manager.py:507 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=29740, ip=127.0.0.1, actor_id=6996c201488ed719bdc6de9b01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001F93EAE98B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,450\tERROR actor_manager.py:507 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=44572, ip=127.0.0.1, actor_id=3804967517b6a22170bd27db01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001E5BEC8C8B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,451\tERROR actor_manager.py:507 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=23176, ip=127.0.0.1, actor_id=b2eb9fc0737bec3d108129bc01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001BB3ED77820>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,451\tERROR actor_manager.py:507 -- Ray error, taking actor 5 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41428, ip=127.0.0.1, actor_id=b23e22583a3b8364a3babdf601000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002593EAE9850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,452\tERROR actor_manager.py:507 -- Ray error, taking actor 6 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=38352, ip=127.0.0.1, actor_id=0ef22395089343aea723d8dd01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001E1BF888850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,453\tERROR actor_manager.py:507 -- Ray error, taking actor 7 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47360, ip=127.0.0.1, actor_id=d9233acb762160a00d4dac3f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D2BEAEB8E0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,454\tERROR actor_manager.py:507 -- Ray error, taking actor 8 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47068, ip=127.0.0.1, actor_id=a6523ae1e8df4d9172b2786301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000192BFAA88E0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,454\tERROR actor_manager.py:507 -- Ray error, taking actor 9 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=42700, ip=127.0.0.1, actor_id=f9a1b1792c595754c6e9ebd801000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000155BF59D850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,455\tERROR actor_manager.py:507 -- Ray error, taking actor 10 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47416, ip=127.0.0.1, actor_id=f035d87850efa65db088f40301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000025DBEAE8820>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,455\tERROR actor_manager.py:507 -- Ray error, taking actor 11 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=14744, ip=127.0.0.1, actor_id=eba0644a0e5184d20bac951901000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001B13EAE9820>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,456\tERROR actor_manager.py:507 -- Ray error, taking actor 12 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=40380, ip=127.0.0.1, actor_id=7df58dc3f5cf15836270c77601000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000246BEAED820>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,456\tERROR actor_manager.py:507 -- Ray error, taking actor 13 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=44768, ip=127.0.0.1, actor_id=569e3cc83705e13532d346c001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001613EAE8850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,457\tERROR actor_manager.py:507 -- Ray error, taking actor 14 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=12720, ip=127.0.0.1, actor_id=8df938d94f780d6cb4ef426f01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D63EC8D7F0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,458\tERROR actor_manager.py:507 -- Ray error, taking actor 15 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41388, ip=127.0.0.1, actor_id=31882bf2f54999f8affbcc4301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000210BEAEC850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:28:33,458\tERROR actor_manager.py:507 -- Ray error, taking actor 16 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=42980, ip=127.0.0.1, actor_id=a6c7f30f73181a23fa30e0fb01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001CCBEAE9880>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n"
     ]
    },
    {
     "ename": "RaySystemError",
     "evalue": "System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayActorError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:172\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[1;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[0;32m    171\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 172\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_setup(\n\u001b[0;32m    173\u001b[0m         validate_env\u001b[39m=\u001b[39;49mvalidate_env,\n\u001b[0;32m    174\u001b[0m         config\u001b[39m=\u001b[39;49mconfig,\n\u001b[0;32m    175\u001b[0m         num_workers\u001b[39m=\u001b[39;49mnum_workers,\n\u001b[0;32m    176\u001b[0m         local_worker\u001b[39m=\u001b[39;49mlocal_worker,\n\u001b[0;32m    177\u001b[0m     )\n\u001b[0;32m    178\u001b[0m \u001b[39m# WorkerSet creation possibly fails, if some (remote) workers cannot\u001b[39;00m\n\u001b[0;32m    179\u001b[0m \u001b[39m# be initialized properly (due to some errors in the RolloutWorker's\u001b[39;00m\n\u001b[0;32m    180\u001b[0m \u001b[39m# constructor).\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:242\u001b[0m, in \u001b[0;36mWorkerSet._setup\u001b[1;34m(self, validate_env, config, num_workers, local_worker)\u001b[0m\n\u001b[0;32m    241\u001b[0m \u001b[39m# Create a number of @ray.remote workers.\u001b[39;00m\n\u001b[1;32m--> 242\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49madd_workers(\n\u001b[0;32m    243\u001b[0m     num_workers,\n\u001b[0;32m    244\u001b[0m     validate\u001b[39m=\u001b[39;49mconfig\u001b[39m.\u001b[39;49mvalidate_workers_after_construction,\n\u001b[0;32m    245\u001b[0m )\n\u001b[0;32m    247\u001b[0m \u001b[39m# If num_workers > 0 and we don't have an env on the local worker,\u001b[39;00m\n\u001b[0;32m    248\u001b[0m \u001b[39m# get the observation- and action spaces for each policy from\u001b[39;00m\n\u001b[0;32m    249\u001b[0m \u001b[39m# the first remote worker (which does have an env).\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:635\u001b[0m, in \u001b[0;36mWorkerSet.add_workers\u001b[1;34m(self, num_workers, validate)\u001b[0m\n\u001b[0;32m    634\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m result\u001b[39m.\u001b[39mok:\n\u001b[1;32m--> 635\u001b[0m     \u001b[39mraise\u001b[39;00m result\u001b[39m.\u001b[39mget()\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py:488\u001b[0m, in \u001b[0;36mFaultTolerantActorManager.__fetch_result\u001b[1;34m(self, remote_actor_ids, remote_calls, tags, timeout_seconds, return_obj_refs, mark_healthy)\u001b[0m\n\u001b[0;32m    487\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 488\u001b[0m     result \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(r)\n\u001b[0;32m    489\u001b[0m     remote_results\u001b[39m.\u001b[39madd_result(actor_id, ResultOrError(result\u001b[39m=\u001b[39mresult), tag)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\auto_init_hook.py:18\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     17\u001b[0m auto_init_ray()\n\u001b[1;32m---> 18\u001b[0m \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    102\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\worker.py:2542\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2541\u001b[0m         \u001b[39melse\u001b[39;00m:\n\u001b[1;32m-> 2542\u001b[0m             \u001b[39mraise\u001b[39;00m value\n\u001b[0;32m   2544\u001b[0m \u001b[39mif\u001b[39;00m is_individual_id:\n",
      "\u001b[1;31mRayActorError\u001b[0m: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41664, ip=127.0.0.1, actor_id=24aeb603d0fa6ac4c067d79001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001FDBF48C850>)\n  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mRaySystemError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[4], line 8\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[39m# register_env(\"snake-mk1-v8\", lambda config: SnakeEnv())\u001b[39;00m\n\u001b[0;32m      5\u001b[0m register_env(\u001b[39m\"\u001b[39m\u001b[39msnake-v8\u001b[39m\u001b[39m\"\u001b[39m, \u001b[39mlambda\u001b[39;00m config: SnakeEnv())\n\u001b[0;32m      7\u001b[0m algo \u001b[39m=\u001b[39m (\n\u001b[1;32m----> 8\u001b[0m     PPOConfig()\n\u001b[0;32m      9\u001b[0m     \u001b[39m.\u001b[39;49mrollouts(num_rollout_workers\u001b[39m=\u001b[39;49m\u001b[39m16\u001b[39;49m,)\n\u001b[0;32m     10\u001b[0m     \u001b[39m.\u001b[39;49mresources(num_gpus\u001b[39m=\u001b[39;49m\u001b[39m1\u001b[39;49m)\n\u001b[0;32m     11\u001b[0m     \u001b[39m.\u001b[39;49menvironment(env\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39msnake-v8\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[0;32m     12\u001b[0m     \u001b[39m.\u001b[39;49mframework(\u001b[39m'\u001b[39;49m\u001b[39mtorch\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[0;32m     13\u001b[0m     \u001b[39m.\u001b[39;49mtraining(gamma\u001b[39m=\u001b[39;49m\u001b[39m0.9\u001b[39;49m, \n\u001b[0;32m     14\u001b[0m               lr\u001b[39m=\u001b[39;49m\u001b[39m0.001\u001b[39;49m,\n\u001b[0;32m     15\u001b[0m               sgd_minibatch_size\u001b[39m=\u001b[39;49m\u001b[39m8192\u001b[39;49m,\n\u001b[0;32m     16\u001b[0m               train_batch_size\u001b[39m=\u001b[39;49m\u001b[39m320000\u001b[39;49m,\n\u001b[0;32m     17\u001b[0m               model\u001b[39m=\u001b[39;49m {\n\u001b[0;32m     18\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mfcnet_hiddens\u001b[39;49m\u001b[39m\"\u001b[39;49m: [\u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m], \n\u001b[0;32m     19\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39muse_lstm\u001b[39;49m\u001b[39m\"\u001b[39;49m : \u001b[39mTrue\u001b[39;49;00m,  \n\u001b[0;32m     20\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mmax_seq_len\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39m150\u001b[39;49m,\n\u001b[0;32m     21\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mlstm_use_prev_action\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m     22\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mlstm_cell_size\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39m256\u001b[39;49m, \n\u001b[0;32m     23\u001b[0m     })\n\u001b[0;32m     24\u001b[0m     \u001b[39m.\u001b[39;49mevaluation(evaluation_interval\u001b[39m=\u001b[39;49m\u001b[39m10\u001b[39;49m)\n\u001b[0;32m     25\u001b[0m     \u001b[39m.\u001b[39;49mbuild()\n\u001b[0;32m     26\u001b[0m )\n\u001b[0;32m     28\u001b[0m algo\u001b[39m.\u001b[39mfrom_checkpoint(\u001b[39m'\u001b[39m\u001b[39mC:\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mUsers\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mBong\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mray_results\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mPPO_snake-v8_Base_925-1050\u001b[39m\u001b[39m\\\\\u001b[39;00m\u001b[39mcheckpoint_001000\u001b[39m\u001b[39m'\u001b[39m)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm_config.py:1071\u001b[0m, in \u001b[0;36mAlgorithmConfig.build\u001b[1;34m(self, env, logger_creator, use_copy)\u001b[0m\n\u001b[0;32m   1068\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class, \u001b[39mstr\u001b[39m):\n\u001b[0;32m   1069\u001b[0m     algo_class \u001b[39m=\u001b[39m get_trainable_cls(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class)\n\u001b[1;32m-> 1071\u001b[0m \u001b[39mreturn\u001b[39;00m algo_class(\n\u001b[0;32m   1072\u001b[0m     config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m \u001b[39mif\u001b[39;49;00m \u001b[39mnot\u001b[39;49;00m use_copy \u001b[39melse\u001b[39;49;00m copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m),\n\u001b[0;32m   1073\u001b[0m     logger_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogger_creator,\n\u001b[0;32m   1074\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:475\u001b[0m, in \u001b[0;36mAlgorithm.__init__\u001b[1;34m(self, config, env, logger_creator, **kwargs)\u001b[0m\n\u001b[0;32m    457\u001b[0m \u001b[39m# Initialize common evaluation_metrics to nan, before they become\u001b[39;00m\n\u001b[0;32m    458\u001b[0m \u001b[39m# available. We want to make sure the metrics are always present\u001b[39;00m\n\u001b[0;32m    459\u001b[0m \u001b[39m# (although their values may be nan), so that Tune does not complain\u001b[39;00m\n\u001b[0;32m    460\u001b[0m \u001b[39m# when we use these as stopping criteria.\u001b[39;00m\n\u001b[0;32m    461\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mevaluation_metrics \u001b[39m=\u001b[39m {\n\u001b[0;32m    462\u001b[0m     \u001b[39m# TODO: Don't dump sampler results into top-level.\u001b[39;00m\n\u001b[0;32m    463\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mevaluation\u001b[39m\u001b[39m\"\u001b[39m: {\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    472\u001b[0m     },\n\u001b[0;32m    473\u001b[0m }\n\u001b[1;32m--> 475\u001b[0m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39m\u001b[39m__init__\u001b[39m(\n\u001b[0;32m    476\u001b[0m     config\u001b[39m=\u001b[39mconfig,\n\u001b[0;32m    477\u001b[0m     logger_creator\u001b[39m=\u001b[39mlogger_creator,\n\u001b[0;32m    478\u001b[0m     \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs,\n\u001b[0;32m    479\u001b[0m )\n\u001b[0;32m    481\u001b[0m \u001b[39m# Check, whether `training_iteration` is still a tune.Trainable property\u001b[39;00m\n\u001b[0;32m    482\u001b[0m \u001b[39m# and has not been overridden by the user in the attempt to implement the\u001b[39;00m\n\u001b[0;32m    483\u001b[0m \u001b[39m# algos logic (this should be done now inside `training_step`).\u001b[39;00m\n\u001b[0;32m    484\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py:170\u001b[0m, in \u001b[0;36mTrainable.__init__\u001b[1;34m(self, config, logger_creator, remote_checkpoint_dir, custom_syncer, sync_timeout, sync_config)\u001b[0m\n\u001b[0;32m    168\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_start_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[0;32m    169\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_local_ip \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39mutil\u001b[39m.\u001b[39mget_node_ip_address()\n\u001b[1;32m--> 170\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msetup(copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig))\n\u001b[0;32m    171\u001b[0m setup_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime() \u001b[39m-\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_start_time\n\u001b[0;32m    172\u001b[0m \u001b[39mif\u001b[39;00m setup_time \u001b[39m>\u001b[39m SETUP_TIME_THRESHOLD:\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:601\u001b[0m, in \u001b[0;36mAlgorithm.setup\u001b[1;34m(self, config)\u001b[0m\n\u001b[0;32m    594\u001b[0m \u001b[39m# Only if user did not override `_init()`:\u001b[39;00m\n\u001b[0;32m    595\u001b[0m \u001b[39mif\u001b[39;00m _init \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m:\n\u001b[0;32m    596\u001b[0m     \u001b[39m# - Create rollout workers here automatically.\u001b[39;00m\n\u001b[0;32m    597\u001b[0m     \u001b[39m# - Run the execution plan to create the local iterator to `next()`\u001b[39;00m\n\u001b[0;32m    598\u001b[0m     \u001b[39m#   in each training iteration.\u001b[39;00m\n\u001b[0;32m    599\u001b[0m     \u001b[39m# This matches the behavior of using `build_trainer()`, which\u001b[39;00m\n\u001b[0;32m    600\u001b[0m     \u001b[39m# has been deprecated.\u001b[39;00m\n\u001b[1;32m--> 601\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mworkers \u001b[39m=\u001b[39m WorkerSet(\n\u001b[0;32m    602\u001b[0m         env_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49menv_creator,\n\u001b[0;32m    603\u001b[0m         validate_env\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mvalidate_env,\n\u001b[0;32m    604\u001b[0m         default_policy_class\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_default_policy_class(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig),\n\u001b[0;32m    605\u001b[0m         config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig,\n\u001b[0;32m    606\u001b[0m         num_workers\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig\u001b[39m.\u001b[39;49mnum_rollout_workers,\n\u001b[0;32m    607\u001b[0m         local_worker\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m    608\u001b[0m         logdir\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogdir,\n\u001b[0;32m    609\u001b[0m     )\n\u001b[0;32m    611\u001b[0m     \u001b[39m# TODO (avnishn): Remove the execution plan API by q1 2023\u001b[39;00m\n\u001b[0;32m    612\u001b[0m     \u001b[39m# Function defining one single training iteration's behavior.\u001b[39;00m\n\u001b[0;32m    613\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconfig\u001b[39m.\u001b[39m_disable_execution_plan_api:\n\u001b[0;32m    614\u001b[0m         \u001b[39m# Ensure remote workers are initially in sync with the local worker.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:194\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[1;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[0;32m    181\u001b[0m \u001b[39mexcept\u001b[39;00m RayActorError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    182\u001b[0m     \u001b[39m# In case of an actor (remote worker) init failure, the remote worker\u001b[39;00m\n\u001b[0;32m    183\u001b[0m     \u001b[39m# may still exist and will be accessible, however, e.g. calling\u001b[39;00m\n\u001b[0;32m    184\u001b[0m     \u001b[39m# its `sample.remote()` would result in strange \"property not found\"\u001b[39;00m\n\u001b[0;32m    185\u001b[0m     \u001b[39m# errors.\u001b[39;00m\n\u001b[0;32m    186\u001b[0m     \u001b[39mif\u001b[39;00m e\u001b[39m.\u001b[39mactor_init_failed:\n\u001b[0;32m    187\u001b[0m         \u001b[39m# Raise the original error here that the RolloutWorker raised\u001b[39;00m\n\u001b[0;32m    188\u001b[0m         \u001b[39m# during its construction process. This is to enforce transparency\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    192\u001b[0m         \u001b[39m# - e.args[0].args[2]: The original Exception (e.g. a ValueError due\u001b[39;00m\n\u001b[0;32m    193\u001b[0m         \u001b[39m# to a config mismatch) thrown inside the actor.\u001b[39;00m\n\u001b[1;32m--> 194\u001b[0m         \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39margs[\u001b[39m0\u001b[39m]\u001b[39m.\u001b[39margs[\u001b[39m2\u001b[39m]\n\u001b[0;32m    195\u001b[0m     \u001b[39m# In any other case, raise the RayActorError as-is.\u001b[39;00m\n\u001b[0;32m    196\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    197\u001b[0m         \u001b[39mraise\u001b[39;00m e\n",
      "\u001b[1;31mRaySystemError\u001b[0m: System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'\n"
     ]
    }
   ],
   "source": [
    "# env = gym.make('snake/SnakeEnv-mk1-v8', render_mode=\"human\")\n",
    "env = gym.make('snake/SnakeEnv-v8', render_mode=\"human\")\n",
    "\n",
    "# register_env(\"snake-mk1-v8\", lambda config: SnakeEnv())\n",
    "register_env(\"snake-v8\", lambda config: SnakeEnv())"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Load pre-learned policy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from ray.rllib.models import ModelCatalog\n",
    "from ray.rllib.models.modelv2 import ModelV2\n",
    "from ray.rllib.models.preprocessors import get_preprocessor\n",
    "from ray.rllib.models.torch.torch_modelv2 import TorchModelV2\n",
    "from ray.rllib.models.torch.recurrent_net import RecurrentNetwork as TorchRNN\n",
    "from ray.rllib.models.tf.recurrent_net import RecurrentNetwork\n",
    "from ray.rllib.utils.annotations import override\n",
    "from ray.rllib.utils.framework import try_import_tf, try_import_torch\n",
    "\n",
    "# load_policy = Policy.from_checkpoint('C:\\\\Users\\\\Bong\\\\ray_results\\\\PPO_snake_mk1_v8_2023-07-13_19-45-351ev0yhrq\\\\checkpoint_000500')\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:442: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "`UnifiedLogger` will be removed in Ray 2.7.\n",
      "  return UnifiedLogger(config, logdir, loggers=None)\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "2023-07-14 18:25:38,580\tINFO worker.py:1627 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32m127.0.0.1:8266 \u001b[39m\u001b[22m\n",
      "\u001b[2m\u001b[36m(pid=44620)\u001b[0m c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\tensorboardx.py:41: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\n",
      "\u001b[2m\u001b[36m(pid=44620)\u001b[0m   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m 2023-07-14 18:25:54,852\tERROR serialization.py:387 -- No module named 'snake_v8'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m ModuleNotFoundError: No module named 'snake_v8'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m 2023-07-14 18:25:55,115\tERROR worker.py:861 -- Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=44620, ip=127.0.0.1, actor_id=bc4296ee59cf0705dde6852301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D13E9EB8B0>)\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m   File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "\u001b[2m\u001b[36m(RolloutWorker pid=44620)\u001b[0m traceback: Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=48016)\u001b[0m c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\logger\\tensorboardx.py:41: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)\u001b[32m [repeated 15x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/ray-logging.html#log-deduplication for more options.)\u001b[0m\n",
      "\u001b[2m\u001b[36m(pid=48016)\u001b[0m   VALID_NP_HPARAMS = (np.bool8, np.float32, np.float64, np.int32, np.int64)\u001b[32m [repeated 15x across cluster]\u001b[0m\n",
      "2023-07-14 18:25:56,923\tERROR actor_manager.py:507 -- Ray error, taking actor 1 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=6864, ip=127.0.0.1, actor_id=d66f3fd48fd53296dbb6a2c001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001BEBE9E6880>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,925\tERROR actor_manager.py:507 -- Ray error, taking actor 2 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=2412, ip=127.0.0.1, actor_id=071e077c44f48e486fd4daf701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000016073D388B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,926\tERROR actor_manager.py:507 -- Ray error, taking actor 3 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=45192, ip=127.0.0.1, actor_id=a4da0418590af29e8891ffd301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A03F97C850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,927\tERROR actor_manager.py:507 -- Ray error, taking actor 4 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41644, ip=127.0.0.1, actor_id=a1b48532eace92ed13f3dc0a01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001B33EA468B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,928\tERROR actor_manager.py:507 -- Ray error, taking actor 5 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=40956, ip=127.0.0.1, actor_id=45645f6e5c221e759bedc15201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001A93EDE88B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,929\tERROR actor_manager.py:507 -- Ray error, taking actor 6 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=44620, ip=127.0.0.1, actor_id=bc4296ee59cf0705dde6852301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001D13E9EB8B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,930\tERROR actor_manager.py:507 -- Ray error, taking actor 7 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=45324, ip=127.0.0.1, actor_id=d86e477b2bd363b8525de03b01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000028F4A5AD7F0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,931\tERROR actor_manager.py:507 -- Ray error, taking actor 8 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=43476, ip=127.0.0.1, actor_id=a4defa18f86779258423c2a301000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001FD782FB7F0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,932\tERROR actor_manager.py:507 -- Ray error, taking actor 9 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=41340, ip=127.0.0.1, actor_id=57dec7933c9dc73b7c939be201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000018C3EAEE7F0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,933\tERROR actor_manager.py:507 -- Ray error, taking actor 10 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=39580, ip=127.0.0.1, actor_id=bc701155e2dcb2cda52903f401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001FC73D38850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,934\tERROR actor_manager.py:507 -- Ray error, taking actor 11 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47996, ip=127.0.0.1, actor_id=1925a5ef45b95673da2fbb1401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002A2BE9FB880>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,935\tERROR actor_manager.py:507 -- Ray error, taking actor 12 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=48016, ip=127.0.0.1, actor_id=3d05d247aaa294dac7eab13601000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000002013E9E88B0>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,936\tERROR actor_manager.py:507 -- Ray error, taking actor 13 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=48032, ip=127.0.0.1, actor_id=c0135b43ef6f66727e6a1a8201000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001BB3E9EC820>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,939\tERROR actor_manager.py:507 -- Ray error, taking actor 14 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47848, ip=127.0.0.1, actor_id=3bee7ae1cfa78be2e17c38d401000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x0000020E3E9EA850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,940\tERROR actor_manager.py:507 -- Ray error, taking actor 15 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=47860, ip=127.0.0.1, actor_id=3821ef122f6e42791f6b6c9d01000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000277BE9E9850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n",
      "2023-07-14 18:25:56,943\tERROR actor_manager.py:507 -- Ray error, taking actor 16 out of service. The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=46084, ip=127.0.0.1, actor_id=244e3d047bc8a4c2439e6e6701000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x00000271BE9E8850>)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\n",
      "ray.exceptions.RaySystemError: System error: No module named 'snake_v8'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n",
      "    obj = self._deserialize_object(data, metadata, object_ref)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "ModuleNotFoundError: No module named 'snake_v8'\n"
     ]
    },
    {
     "ename": "RaySystemError",
     "evalue": "System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'\n",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayActorError\u001b[0m                             Traceback (most recent call last)",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:172\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[1;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[0;32m    171\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 172\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_setup(\n\u001b[0;32m    173\u001b[0m         validate_env\u001b[39m=\u001b[39;49mvalidate_env,\n\u001b[0;32m    174\u001b[0m         config\u001b[39m=\u001b[39;49mconfig,\n\u001b[0;32m    175\u001b[0m         num_workers\u001b[39m=\u001b[39;49mnum_workers,\n\u001b[0;32m    176\u001b[0m         local_worker\u001b[39m=\u001b[39;49mlocal_worker,\n\u001b[0;32m    177\u001b[0m     )\n\u001b[0;32m    178\u001b[0m \u001b[39m# WorkerSet creation possibly fails, if some (remote) workers cannot\u001b[39;00m\n\u001b[0;32m    179\u001b[0m \u001b[39m# be initialized properly (due to some errors in the RolloutWorker's\u001b[39;00m\n\u001b[0;32m    180\u001b[0m \u001b[39m# constructor).\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:242\u001b[0m, in \u001b[0;36mWorkerSet._setup\u001b[1;34m(self, validate_env, config, num_workers, local_worker)\u001b[0m\n\u001b[0;32m    241\u001b[0m \u001b[39m# Create a number of @ray.remote workers.\u001b[39;00m\n\u001b[1;32m--> 242\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49madd_workers(\n\u001b[0;32m    243\u001b[0m     num_workers,\n\u001b[0;32m    244\u001b[0m     validate\u001b[39m=\u001b[39;49mconfig\u001b[39m.\u001b[39;49mvalidate_workers_after_construction,\n\u001b[0;32m    245\u001b[0m )\n\u001b[0;32m    247\u001b[0m \u001b[39m# If num_workers > 0 and we don't have an env on the local worker,\u001b[39;00m\n\u001b[0;32m    248\u001b[0m \u001b[39m# get the observation- and action spaces for each policy from\u001b[39;00m\n\u001b[0;32m    249\u001b[0m \u001b[39m# the first remote worker (which does have an env).\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:635\u001b[0m, in \u001b[0;36mWorkerSet.add_workers\u001b[1;34m(self, num_workers, validate)\u001b[0m\n\u001b[0;32m    634\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m result\u001b[39m.\u001b[39mok:\n\u001b[1;32m--> 635\u001b[0m     \u001b[39mraise\u001b[39;00m result\u001b[39m.\u001b[39mget()\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\utils\\actor_manager.py:488\u001b[0m, in \u001b[0;36mFaultTolerantActorManager.__fetch_result\u001b[1;34m(self, remote_actor_ids, remote_calls, tags, timeout_seconds, return_obj_refs, mark_healthy)\u001b[0m\n\u001b[0;32m    487\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> 488\u001b[0m     result \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(r)\n\u001b[0;32m    489\u001b[0m     remote_results\u001b[39m.\u001b[39madd_result(actor_id, ResultOrError(result\u001b[39m=\u001b[39mresult), tag)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\auto_init_hook.py:18\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     17\u001b[0m auto_init_ray()\n\u001b[1;32m---> 18\u001b[0m \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    102\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> 103\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\worker.py:2542\u001b[0m, in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   2541\u001b[0m         \u001b[39melse\u001b[39;00m:\n\u001b[1;32m-> 2542\u001b[0m             \u001b[39mraise\u001b[39;00m value\n\u001b[0;32m   2544\u001b[0m \u001b[39mif\u001b[39;00m is_individual_id:\n",
      "\u001b[1;31mRayActorError\u001b[0m: The actor died because of an error raised in its creation task, \u001b[36mray::RolloutWorker.__init__()\u001b[39m (pid=6864, ip=127.0.0.1, actor_id=d66f3fd48fd53296dbb6a2c001000000, repr=<ray.rllib.evaluation.rollout_worker.RolloutWorker object at 0x000001BEBE9E6880>)\n  File \"python\\ray\\_raylet.pyx\", line 1383, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 1417, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 775, in ray._raylet.raise_if_dependency_failed\nray.exceptions.RaySystemError: System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mRaySystemError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[3], line 2\u001b[0m\n\u001b[0;32m      1\u001b[0m algo \u001b[39m=\u001b[39m (\n\u001b[1;32m----> 2\u001b[0m     PPOConfig()\n\u001b[0;32m      3\u001b[0m     \u001b[39m.\u001b[39;49mrollouts(num_rollout_workers\u001b[39m=\u001b[39;49m\u001b[39m16\u001b[39;49m,)\n\u001b[0;32m      4\u001b[0m     \u001b[39m.\u001b[39;49mresources(num_gpus\u001b[39m=\u001b[39;49m\u001b[39m1\u001b[39;49m)\n\u001b[0;32m      5\u001b[0m     \u001b[39m.\u001b[39;49menvironment(env\u001b[39m=\u001b[39;49m\u001b[39m\"\u001b[39;49m\u001b[39msnake-v8\u001b[39;49m\u001b[39m\"\u001b[39;49m)\n\u001b[0;32m      6\u001b[0m     \u001b[39m.\u001b[39;49mframework(\u001b[39m'\u001b[39;49m\u001b[39mtorch\u001b[39;49m\u001b[39m'\u001b[39;49m)\n\u001b[0;32m      7\u001b[0m     \u001b[39m.\u001b[39;49mtraining(gamma\u001b[39m=\u001b[39;49m\u001b[39m0.9\u001b[39;49m, \n\u001b[0;32m      8\u001b[0m               lr\u001b[39m=\u001b[39;49m\u001b[39m0.001\u001b[39;49m,\n\u001b[0;32m      9\u001b[0m               sgd_minibatch_size\u001b[39m=\u001b[39;49m\u001b[39m8192\u001b[39;49m,\n\u001b[0;32m     10\u001b[0m               train_batch_size\u001b[39m=\u001b[39;49m\u001b[39m320000\u001b[39;49m,\n\u001b[0;32m     11\u001b[0m               model\u001b[39m=\u001b[39;49m {\n\u001b[0;32m     12\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mfcnet_hiddens\u001b[39;49m\u001b[39m\"\u001b[39;49m: [\u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m, \u001b[39m512\u001b[39;49m], \n\u001b[0;32m     13\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39muse_lstm\u001b[39;49m\u001b[39m\"\u001b[39;49m : \u001b[39mTrue\u001b[39;49;00m,  \n\u001b[0;32m     14\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mmax_seq_len\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39m150\u001b[39;49m,\n\u001b[0;32m     15\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mlstm_use_prev_action\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m     16\u001b[0m         \u001b[39m\"\u001b[39;49m\u001b[39mlstm_cell_size\u001b[39;49m\u001b[39m\"\u001b[39;49m: \u001b[39m256\u001b[39;49m, \n\u001b[0;32m     17\u001b[0m     })\n\u001b[0;32m     18\u001b[0m     \u001b[39m.\u001b[39;49mevaluation(evaluation_interval\u001b[39m=\u001b[39;49m\u001b[39m10\u001b[39;49m)\n\u001b[0;32m     19\u001b[0m     \u001b[39m.\u001b[39;49mbuild()\n\u001b[0;32m     20\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm_config.py:1071\u001b[0m, in \u001b[0;36mAlgorithmConfig.build\u001b[1;34m(self, env, logger_creator, use_copy)\u001b[0m\n\u001b[0;32m   1068\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class, \u001b[39mstr\u001b[39m):\n\u001b[0;32m   1069\u001b[0m     algo_class \u001b[39m=\u001b[39m get_trainable_cls(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39malgo_class)\n\u001b[1;32m-> 1071\u001b[0m \u001b[39mreturn\u001b[39;00m algo_class(\n\u001b[0;32m   1072\u001b[0m     config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m \u001b[39mif\u001b[39;49;00m \u001b[39mnot\u001b[39;49;00m use_copy \u001b[39melse\u001b[39;49;00m copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m),\n\u001b[0;32m   1073\u001b[0m     logger_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogger_creator,\n\u001b[0;32m   1074\u001b[0m )\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:475\u001b[0m, in \u001b[0;36mAlgorithm.__init__\u001b[1;34m(self, config, env, logger_creator, **kwargs)\u001b[0m\n\u001b[0;32m    457\u001b[0m \u001b[39m# Initialize common evaluation_metrics to nan, before they become\u001b[39;00m\n\u001b[0;32m    458\u001b[0m \u001b[39m# available. We want to make sure the metrics are always present\u001b[39;00m\n\u001b[0;32m    459\u001b[0m \u001b[39m# (although their values may be nan), so that Tune does not complain\u001b[39;00m\n\u001b[0;32m    460\u001b[0m \u001b[39m# when we use these as stopping criteria.\u001b[39;00m\n\u001b[0;32m    461\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mevaluation_metrics \u001b[39m=\u001b[39m {\n\u001b[0;32m    462\u001b[0m     \u001b[39m# TODO: Don't dump sampler results into top-level.\u001b[39;00m\n\u001b[0;32m    463\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mevaluation\u001b[39m\u001b[39m\"\u001b[39m: {\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    472\u001b[0m     },\n\u001b[0;32m    473\u001b[0m }\n\u001b[1;32m--> 475\u001b[0m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39m\u001b[39m__init__\u001b[39m(\n\u001b[0;32m    476\u001b[0m     config\u001b[39m=\u001b[39mconfig,\n\u001b[0;32m    477\u001b[0m     logger_creator\u001b[39m=\u001b[39mlogger_creator,\n\u001b[0;32m    478\u001b[0m     \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs,\n\u001b[0;32m    479\u001b[0m )\n\u001b[0;32m    481\u001b[0m \u001b[39m# Check, whether `training_iteration` is still a tune.Trainable property\u001b[39;00m\n\u001b[0;32m    482\u001b[0m \u001b[39m# and has not been overridden by the user in the attempt to implement the\u001b[39;00m\n\u001b[0;32m    483\u001b[0m \u001b[39m# algos logic (this should be done now inside `training_step`).\u001b[39;00m\n\u001b[0;32m    484\u001b[0m \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\tune\\trainable\\trainable.py:170\u001b[0m, in \u001b[0;36mTrainable.__init__\u001b[1;34m(self, config, logger_creator, remote_checkpoint_dir, custom_syncer, sync_timeout, sync_config)\u001b[0m\n\u001b[0;32m    168\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_start_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[0;32m    169\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_local_ip \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39mutil\u001b[39m.\u001b[39mget_node_ip_address()\n\u001b[1;32m--> 170\u001b[0m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msetup(copy\u001b[39m.\u001b[39;49mdeepcopy(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig))\n\u001b[0;32m    171\u001b[0m setup_time \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime() \u001b[39m-\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_start_time\n\u001b[0;32m    172\u001b[0m \u001b[39mif\u001b[39;00m setup_time \u001b[39m>\u001b[39m SETUP_TIME_THRESHOLD:\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:601\u001b[0m, in \u001b[0;36mAlgorithm.setup\u001b[1;34m(self, config)\u001b[0m\n\u001b[0;32m    594\u001b[0m \u001b[39m# Only if user did not override `_init()`:\u001b[39;00m\n\u001b[0;32m    595\u001b[0m \u001b[39mif\u001b[39;00m _init \u001b[39mis\u001b[39;00m \u001b[39mFalse\u001b[39;00m:\n\u001b[0;32m    596\u001b[0m     \u001b[39m# - Create rollout workers here automatically.\u001b[39;00m\n\u001b[0;32m    597\u001b[0m     \u001b[39m# - Run the execution plan to create the local iterator to `next()`\u001b[39;00m\n\u001b[0;32m    598\u001b[0m     \u001b[39m#   in each training iteration.\u001b[39;00m\n\u001b[0;32m    599\u001b[0m     \u001b[39m# This matches the behavior of using `build_trainer()`, which\u001b[39;00m\n\u001b[0;32m    600\u001b[0m     \u001b[39m# has been deprecated.\u001b[39;00m\n\u001b[1;32m--> 601\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mworkers \u001b[39m=\u001b[39m WorkerSet(\n\u001b[0;32m    602\u001b[0m         env_creator\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49menv_creator,\n\u001b[0;32m    603\u001b[0m         validate_env\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mvalidate_env,\n\u001b[0;32m    604\u001b[0m         default_policy_class\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mget_default_policy_class(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig),\n\u001b[0;32m    605\u001b[0m         config\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig,\n\u001b[0;32m    606\u001b[0m         num_workers\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconfig\u001b[39m.\u001b[39;49mnum_rollout_workers,\n\u001b[0;32m    607\u001b[0m         local_worker\u001b[39m=\u001b[39;49m\u001b[39mTrue\u001b[39;49;00m,\n\u001b[0;32m    608\u001b[0m         logdir\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mlogdir,\n\u001b[0;32m    609\u001b[0m     )\n\u001b[0;32m    611\u001b[0m     \u001b[39m# TODO (avnishn): Remove the execution plan API by q1 2023\u001b[39;00m\n\u001b[0;32m    612\u001b[0m     \u001b[39m# Function defining one single training iteration's behavior.\u001b[39;00m\n\u001b[0;32m    613\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mconfig\u001b[39m.\u001b[39m_disable_execution_plan_api:\n\u001b[0;32m    614\u001b[0m         \u001b[39m# Ensure remote workers are initially in sync with the local worker.\u001b[39;00m\n",
      "File \u001b[1;32mc:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\rllib\\evaluation\\worker_set.py:194\u001b[0m, in \u001b[0;36mWorkerSet.__init__\u001b[1;34m(self, env_creator, validate_env, default_policy_class, config, num_workers, local_worker, logdir, _setup, policy_class, trainer_config)\u001b[0m\n\u001b[0;32m    181\u001b[0m \u001b[39mexcept\u001b[39;00m RayActorError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m    182\u001b[0m     \u001b[39m# In case of an actor (remote worker) init failure, the remote worker\u001b[39;00m\n\u001b[0;32m    183\u001b[0m     \u001b[39m# may still exist and will be accessible, however, e.g. calling\u001b[39;00m\n\u001b[0;32m    184\u001b[0m     \u001b[39m# its `sample.remote()` would result in strange \"property not found\"\u001b[39;00m\n\u001b[0;32m    185\u001b[0m     \u001b[39m# errors.\u001b[39;00m\n\u001b[0;32m    186\u001b[0m     \u001b[39mif\u001b[39;00m e\u001b[39m.\u001b[39mactor_init_failed:\n\u001b[0;32m    187\u001b[0m         \u001b[39m# Raise the original error here that the RolloutWorker raised\u001b[39;00m\n\u001b[0;32m    188\u001b[0m         \u001b[39m# during its construction process. This is to enforce transparency\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    192\u001b[0m         \u001b[39m# - e.args[0].args[2]: The original Exception (e.g. a ValueError due\u001b[39;00m\n\u001b[0;32m    193\u001b[0m         \u001b[39m# to a config mismatch) thrown inside the actor.\u001b[39;00m\n\u001b[1;32m--> 194\u001b[0m         \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39margs[\u001b[39m0\u001b[39m]\u001b[39m.\u001b[39margs[\u001b[39m2\u001b[39m]\n\u001b[0;32m    195\u001b[0m     \u001b[39m# In any other case, raise the RayActorError as-is.\u001b[39;00m\n\u001b[0;32m    196\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    197\u001b[0m         \u001b[39mraise\u001b[39;00m e\n",
      "\u001b[1;31mRaySystemError\u001b[0m: System error: No module named 'snake_v8'\ntraceback: Traceback (most recent call last):\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 385, in deserialize_objects\n    obj = self._deserialize_object(data, metadata, object_ref)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 268, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 223, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"c:\\Users\\Bong\\anaconda3\\envs\\rllib\\lib\\site-packages\\ray\\_private\\serialization.py\", line 213, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\nModuleNotFoundError: No module named 'snake_v8'\n"
     ]
    }
   ],
   "source": [
    "algo = (\n",
    "    PPOConfig()\n",
    "    .rollouts(num_rollout_workers=16,)\n",
    "    .resources(num_gpus=1)\n",
    "    .environment(env=\"snake-v8\")\n",
    "    .framework('torch')\n",
    "    .training(gamma=0.9, \n",
    "              lr=0.001,\n",
    "              sgd_minibatch_size=8192,\n",
    "              train_batch_size=320000,\n",
    "              model= {\n",
    "        \"fcnet_hiddens\": [512, 512, 512, 512, 512, 512], \n",
    "        \"use_lstm\" : True,  \n",
    "        \"max_seq_len\": 150,\n",
    "        \"lstm_use_prev_action\": True,\n",
    "        \"lstm_cell_size\": 256, \n",
    "    })\n",
    "    .evaluation(evaluation_interval=10)\n",
    "    .build()\n",
    ")\n",
    "\n",
    "algo.from_checkpoint('C:\\\\Users\\\\Bong\\\\ray_results\\\\PPO_snake-v8_Base_925-1050\\\\checkpoint_001000')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "load_policy = Policy.from_checkpoint('C:\\\\Users\\\\Bong\\\\ray_results\\\\PPO_snake-v8_Base_925-1050\\\\checkpoint_001000')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "## For Recurrent Policy\n",
    "\n",
    "# lstm_dim = 64\n",
    "# num_lstm_cells = 2\n",
    "# initial_state = np.zeros((num_lstm_cells, lstm_dim))\n",
    "\n",
    "_state = load_policy['default_policy'].get_initial_state()\n",
    "_prev_action = np.zeros(14,)\n",
    "_reward = 0\n",
    "_obs, _ = env.reset()\n",
    "_accum_reward = 0\n",
    "\n",
    "for epi in range(1):\n",
    "    for i in range(1870):\n",
    "        _act, _state, _ = load_policy['default_policy'].compute_single_action(obs=_obs.copy(), state=_state.copy(), prev_action=_prev_action.copy(), prev_reward=_reward)\n",
    "        _prev_action = _act.copy()\n",
    "        # print(_act)\n",
    "        _obs, _reward, _done, _, _dict = env.step(_act)\n",
    "        _accum_reward = _accum_reward + _reward\n",
    "\n",
    "        if _done:\n",
    "            break\n",
    "\n",
    "        # print(str(_accum_reward)+\"  \\r\",end='')\n",
    "        # print(f\"{_dict['head_rotation']}\")\n",
    "        # print(_dict['forward_reward'])\n",
    "    _obs, _ = env.reset()\n",
    "    _accum_reward = 0\n",
    "    print(\"episode done...\")\n",
    "    print(_accum_reward)\n",
    "env.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "load_policy['default_policy'].model.get_parameter"
   ]
  },
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Do simulation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "_obs, _ = env.reset()\n",
    "\n",
    "c_reward = 0\n",
    "for epi in range(10):\n",
    "    for i in range(1400):\n",
    "        _act = load_policy['default_policy'].compute_single_action(_obs)\n",
    "        _obs, _reward, _, _, _ = env.step(_act[0])\n",
    "        c_reward = c_reward + _reward\n",
    "    _obs, _ = env.reset()\n",
    "    print(c_reward)\n",
    "    c_reward = 0\n",
    "    \n",
    "env.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "_state = load_policy['default_policy'].get_initial_state()\n",
    "_state = np.tile(_state,(10,1))\n",
    "# _state = np.concatenate(_state)\n",
    "\n",
    "env.close()\n",
    "# _obs, _ = env.reset()\n",
    "\n",
    "_act, _state, _ = load_policy['default_policy'].compute_single_action(obs=_obs, state=_state)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "rllib",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.16"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "d47bedaa1c91cdd818b14831e10e7cdc4f0653b726a0327bbea2da1503325d29"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
